### ISSUE TITLE
Make package available via MELPA Stable. 

### ISSUE THREAD

**Issue by adc17** [timcharper/evil-surround#100]
Hey Tim,

[MELPA Stable](http://stable.melpa.org/) is a version of MELPA for users who'd rather run only stable versions of packages (MELPA can be a bit rocky since every commit comprises a new release), and it would be great if evil-surround could be installed via Stable.

As I understand it, all you have to do is define a tag in the v... format and you're done. So if you're on board with the idea, this should be all you have to do to make it happen:

$ git tag v1.0.0 fe6351b8fe8553db59b52f48f9bb6e72bf0aa701
$ git push origin v1.0.0

(Of course, this assumes that fe6351b is an appropriate commit for a release.) 

Thanks for your time and consideration!

**Comment by ninrod** [comment]
Hi. I'm the current mantainer as @timcharper is engaged in other OSS projects. I've just uploaded the tag. Let me know if this solves stable melpa issue.

**Comment by adc17** [comment]
Perfect, it's there! Thanks for resolving this so quickly @ninrod.

**Comment by ninrod** [comment]
Ok, I think we can close this safely then.
