### ISSUE TITLE
ys}} does not insert newline before the '}' unless at line-beginning

### ISSUE THREAD

**Issue by unhammer** [timcharper/evil-surround#103]
say point is ☐ in
```
  if(thing)  ☐
    return 1;

  dostuff();
```
and I hit `ys}}`, then I get

```
  if(thing)  ☐{
    return 1;}

  dostuff();
```

I'd much prefer to get:

```
  if(thing)  ☐{
    return 1;
  }

  dostuff();
```

Is this a bug? If not, is there a simple way to do this while still getting the right indentation on the final `}`? (I do get the newline if point is at beginning of line, but that's not very useful here.)

**Comment by ninrod** [comment]
As we don't have a text object that correctly describes those locations, it is difficult to do that from normal mode. But you can do what you want in visual mode through the `S` operator.

select from point up to the end of the second line. then press `S` then `}`.

**Comment by unhammer** [comment]
OK, so the solution is either a bit of typing or I define a text object :-) Thanks for the answer. I guess this can be closed.
