### ISSUE TITLE
FR: delete|change closest surround pair

### ISSUE THREAD

**Issue by xged** [timcharper/evil-surround#106]
This is what you want 99% of the time, no need to specify the char.

**Comment by ninrod** [comment]
hum, very interesting.

**Comment by xged** [comment]
`sp-splice-sexp` (*smartparens*) acts similarly.

**Comment by ninrod** [comment]
interestingly enough, this is already working for me. 
cursor in `[]`

```txt
[]                                   (foo)
```

I type `dib` and the parentheses is gone.

**Comment by ninrod** [comment]
Yep. confirmed. The functionality you want is already available through the [targets.el](https://github.com/noctuid/targets.el) package.

And I'd prefer to keep that way. Seeking forward is the job of the targets.el package.
