### ISSUE TITLE
Tilde for surround-pars in org-mode doesn't work

### ISSUE THREAD

**Issue by HongxuChen** [timcharper/evil-surround#20]
I add `(push '(?~ . ("~" . "~")) surround-pairs-alis` as a hook for org-mode and now the _surround-pairs-alist_ is:

``` lisp
((61 "=" . "=")
 (126 "~" . "~")
 (40 "( " . " )")
 (91 "[ " . " ]")
 (123 "{ " . " }")
 (41 "(" . ")")
 (93 "[" . "]")
 (125 "{" . "}")
 (35 "#{" . "}")
 (98 "(" . ")")
 (66 "{" . "}")
 (62 "<" . ">")
 (116 . surround-read-tag)
 (60 . surround-read-tag)
```

But I cannot use `cs~*` for `~test~`; it also fails with `=test=`.
BTW, evil-surround works smoothly for default pairs like `cs"'` for `"test"` in org-mode.

**Comment by fleimgruber** [comment]
@HongxuChen I had a shot at it, see https://github.com/edwtjo/evil-org-mode/pull/30. Would be good to know whether that works for you.

**Comment by ninrod** [comment]
So can we close this?

**Comment by Copper-Head** [comment]
Actually this isn't fixed, since that PR wasn't merged. Or am I missing something? I can't get it to work in my setup currently.

**Comment by ninrod** [comment]
See this [entry](https://github.com/emacs-evil/evil-surround#add-new-surround-pairs-through-creation-of-evil-objects) in the readme. 

Just define the macro and apply it, like this: 

```elisp
;; define the macro
(defmacro define-and-bind-quoted-text-object (name key start-regex end-regex)
  (let ((inner-name (make-symbol (concat "evil-inner-" name)))
        (outer-name (make-symbol (concat "evil-a-" name))))
    `(progn
       (evil-define-text-object ,inner-name (count &optional beg end type)
         (evil-select-paren ,start-regex ,end-regex beg end type count nil))
       (evil-define-text-object ,outer-name (count &optional beg end type)
         (evil-select-paren ,start-regex ,end-regex beg end type count t))
       (define-key evil-inner-text-objects-map ,key #',inner-name)
       (define-key evil-outer-text-objects-map ,key #',outer-name))))

;; apply it to the object you are interested in:
(define-and-bind-quoted-text-object "dollar" "~" "~" "~")
```

**Comment by Copper-Head** [comment]
@ninrod Thanks, I got it to work! The docs are a bit out of date because the SO answer they reference has been updated, I'll try to open a PR sometime soon to fix them up.
