### ISSUE TITLE
change keybindings

### ISSUE THREAD

**Issue by mygnu** [timcharper/evil-surround#33]
Hi all
I use Dvorak keyboard, and have s key already binded. how to change "s" to "k" in visual mode.
I've tried 
(evil-define-key 'operator surround-mode-map "k" 'surround-edit)
(evil-define-key 'visual surround-mode-map "k" 'surround-region)
(evil-define-key 'visual surround-mode-map "K" 'Surround-region)
and 
 (define-key evil-visual-state-map "k" 'surround-region)
with no success.
Can anyone please help.
Thanks

**Comment by wbolster** [comment]
is this issue still relevant? it looks like this package no longer hardcodes keys.

**Comment by mygnu** [comment]
not using it anymore :(
