### ISSUE TITLE
Old "surround" package still available on marmalade

### ISSUE THREAD

**Issue by AshleyMoni** [timcharper/evil-surround#37]
My package-archives includes elpa, melpa and marmalade.

It took me a while to figure out what the difference was between "surround" and "evil-surround"; the latter is a renamed version of the former. Surround should probably be removed from the repository to stop people downloading the old version (and stop confusion in general); I was using surround for a while myself.

**Comment by ninrod** [comment]
Hi I'm the new mantainer for the season. Is this still an issue?

**Comment by ninrod** [comment]
Seeing as marmaled-repo.org gives me `502 bad gateway`, and obvserving that melpa.org is really the de facto standard in 2017, I think we can safely close this.
