### ISSUE TITLE
yss doesn't ignore the leading whitespace

### ISSUE THREAD

**Issue by godblessfq** [timcharper/evil-surround#39]
I learned from here http://kana.github.io/config/vim/surround.html that yss should operates on the current line, ignoring leading whitespace. But it always includes the leading whitespace on my machine, which looks bad. I am using emacs 24.3.
Any ideas?
Thank you!

**Comment by timcharper** [comment]
Fixed with https://github.com/timcharper/evil-surround/commit/8b2ca83b7cdc4ef76aa9a1af7797b70d1cb25a5e
