### ISSUE TITLE
Can't delete function call using `dsf`.

### ISSUE THREAD

**Issue by tmalsburg** [timcharper/evil-surround#41]
Since it's possible to wrap a text object in a function call with, e.g.,  `yssf`, I would expect `dsf` to delete that function call. Seems like a very useful feature.

**Comment by TheBB** [comment]
I would like to work on this problem. It plagues more than just the function surround, also things like https://github.com/timcharper/evil-surround/issues/69. Is there no word from @timcharper on how he would like this to look?

**Comment by Ramapitecus** [comment]
well, I stopped using evil since then for vanilla emacs. My implementation worked just fine for me. It deleted the surrounding function, but I didn't get around at implementing changing the surrounding function. IIRC. Tim proposed this addition to vim surround and it wasn't accepted so he didn't include it here for compatibility with the original. I may be wrong though.

**Comment by timcharper** [comment]
Yeah, this project targets compatibility with vim.surround... for... reasons. The plugin, right now (for the most part...), doesn't have any special considerations for different major modes. I'd like to keep it that way. There's no standard Emacs way to define an overlay for a function. It just doesn't exist. This feature would require a special function for every major mode people use.

If you come up with a snippet that people can paste in to their `.emacs`, and is reasonably extensible, I'll totally link to it from the README!

**Comment by TheBB** [comment]
> This feature would require a special function for every major mode people use.

Adding a surrounding function isn't specialized by major mode either, though. The feature I was looking for was for `dsf` to remove precisely what `v<...>sf` adds.

**Comment by timcharper** [comment]
Those keybindings don't seem to work for me. And, I'm not sure what you mean by "adding a surrounding function isn't specialized by major mode". It's syntax specific. In `emacs-lisp-mode`, surrounding with a function is done with `(defun fn-name (...))`. In ruby, it's `def fn_name; ...; end`. In Scala, it's `def fnName = {}`.

**Comment by TheBB** [comment]
Really? That's not what I'm seeing. Let me use non-visual state so the bindings are the same. For example with cursor on the word `word` the key sequence `ysiwfa<RET>` produces `a(word)` in Emacs Lisp mode, not `(a word)` which is what I would have expected if it were syntax aware.

Are we talking about the same thing?

**Comment by timcharper** [comment]
Okay; I've never used the key sequence. You're right, it does work, and it doesn't the right thing lisps (it assumes that all functions in all modes are called with `identifier(params)`, and never `(identifier params)`, corroborating my point that language specific support would be required.

**Comment by timcharper** [comment]
Is this supported in `vim.surround`, though? It sounded like @tpope shied away from it.

**Comment by timcharper** [comment]
https://github.com/tpope/vim-surround/issues/157

**Comment by timcharper** [comment]
https://github.com/tpope/vim-surround/pull/118

**Comment by braham-snyder** [comment]
for those seeking a quick fix, https://github.com/cute-jumper/embrace.el combined with evil-embrace (linked there--hooks into evil-surround with one line) allows (non-language-aware) dsf and csf

**Comment by tmalsburg** [comment]
Awesome, thanks for sharing, @braham-snyder.

**Comment by ninrod** [comment]
With the existence of evil-embrace, I think we can close this now.
