### ISSUE TITLE
Incorrect cursor position after undo

### ISSUE THREAD

**Issue by tmalsburg** [timcharper/evil-surround#43]
The pipe indicates the cursor position:

```
This is a test |sentence.
```

`yssfprint`

```
|print(This is a test sentence.)
```

`C-_`

```
|This is a test sentence.
```

The expexted result is:

```
This is a test |sentence.
```

The same happens when I add a tag instead of a function call.  However, adding quotes and undoing puts the cursor in the original position.

**Comment by ninrod** [comment]
@tmalsburg closing because #44 was closed by @timcharper.
