### ISSUE TITLE
Documentation inaccuracy

### ISSUE THREAD

**Issue by AshleyMoni** [timcharper/evil-surround#45]
The documentation for `evil-surround-edit` is inaccurate when compared to the code for the function itself.

The documentation string:

    "Edit the surrounding delimiters represented by CHAR.
    If OPERATION is `change', call `evil-surround-change'.
    if OPERATION is `surround', call `evil-surround-region'.
    Otherwise call `evil-surround-delete'."

The actual conditional branch is a cond that checks if the operation is `'change`, then checks if it's `'delete`, and then ultimately calls `evil-surround-region`.

The proper documentation string should be:

    "Edit the surrounding delimiters represented by CHAR.
    If OPERATION is `change', call `evil-surround-change'.
    if OPERATION is `delete', call `evil-surround-delete'.
    Otherwise call `evil-surround-region'."

**Comment by timcharper** [comment]
Was resolved in 5e6bcb38e9b36506a8a0554f47cd00947e84ac0d

(although.. typo)
