### ISSUE TITLE
Wrapping entire line behaves other than surround.vim

### ISSUE THREAD

**Issue by cofi** [timcharper/evil-surround#5]
I'm currently working on some patches, one would add a documentation.
I draw on the examples from surround.vim and there is`yssb` on this line:

     { Hello } world!

The expected would be

     ({ Hello } world!)

but it is (make emacs on the latest evil)

    (
     { Hello } world!
       )

I'm not sure if the problem lies with evil's sentence (line?) text object or evil-surround but since I can only think of surround to reproduce this I'll submit it here.

**Comment by blaenk** [comment]
This can be closed it seems.

**Comment by timcharper** [comment]
Fixed with https://github.com/timcharper/evil-surround/commit/8b2ca83b7cdc4ef76aa9a1af7797b70d1cb25a5e
