### ISSUE TITLE
Escape inserts literal escape instead of quitting

### ISSUE THREAD

**Issue by rpglover64** [timcharper/evil-surround#51]
1. Be in visual mode
2. Press <kbd>s</kbd>
3. Press <kbd>Esc</kbd>

Expected: Return to visual mode without any surrounding characters
Got: `^[` surrounding the visual region

Copied from syl20bnr/spacemacs/issues/814.

**Comment by hlissner** [comment]
This is my workaround. P

`(push '(?\C-\[ . ("" . "")) evil-surround-pairs-alist)`
