### ISSUE TITLE
yss should not add new lines

### ISSUE THREAD

**Issue by sotte** [timcharper/evil-surround#52]
Given a text
```
some text
```
`yss)` should surround the entire line without adding new lines.
```
(some text)
```
but evil-surround adds the () on new lines
```
(
some text
)
```

**Comment by PierreR** [comment]
Same problem for me except that I have this:
```
hi { Hello } world! 
```
yss)
gives:
```
(
hi { Hello } world!)
```

**Comment by timcharper** [comment]
Confirmed.

**Comment by leoalekseyev** [comment]
Just ran across this, couldn't tell if it was a bug or not with the recent-ish s vs S changes... Hope it gets fixed.

**Comment by levelel** [comment]
yss` still pushed the last ` character to the new line. Same as other special characters, eg. # & *, etc. Is this intended?
