### ISSUE TITLE
Should surround-operator-alist be evil-surround-operator-alist?

### ISSUE THREAD

**Issue by Drolyt** [timcharper/evil-surround#55]
In the documentation it is suggested to fix the conflict with evil-paredit with the following snippet:
```emacs-lisp
(add-to-list 'surround-operator-alist
             '(evil-paredit-change . change))
(add-to-list 'surround-operator-alist
             '(evil-paredit-delete . delete))
```
However, surround-operator-alist does not appear to be an actual variable. Is this supposed to be evil-surround-operator-alist?

**Comment by expez** [comment]
yes, the package was renamed a while back
