### ISSUE TITLE
Nested commands act upon parent rather than child.

### ISSUE THREAD

**Issue by lethjakman** [timcharper/evil-surround#59]
If you run have a string like the following

    .where(['some query'], %w(additional stuff here)]) 

And with your curser on the "a" in additional and run the command "di(" it will generate the string:

    .where()

rather than:

    .where(['some query'], %w()])

This seems to happen on all nested commands.

**Comment by timcharper** [comment]
This is probably a side effect with the Emacs grammar you are using; it's likely parsing `%w(...)` differently than `(...)`, and evil doesn't text-object / overlay created by the former.

Also, the feature you describe, `di(`, is a feature of evil itself, not this project. Closing for that reason.
