### ISSUE TITLE
surround in insert mode

### ISSUE THREAD

**Issue by igoralmeida** [timcharper/evil-surround#65]
Hi guys,

In vim I'm used to adding delimiters (e.g. parens) in insert mode with CTRL-s ), and I combine this with 'let g:surround_insert_tail = "<++>"' and imaps.vim to then jump to the marking with CTRL-j. Is such a thing possible with evil-surround? I don't really mind removing the search functionality from CTRL-s.

**Comment by igoralmeida** [comment]
I'm still struggling with elisp, can anyone suggest a way to implement this functionality? I see that `evil-surround-edit` is the dispatcher, so my first attempt was
`(evil-define-key 'insert evil-surround-mode-map "C-s" 'evil-surround-edit)`

... but that doesn't do what I want. So what could I be missing (besides a way to unmap isearch-forward)?

**Comment by ninrod** [comment]
is this still an issue for you?

**Comment by igoralmeida** [comment]
I never managed to do it, so yes. But I am no longer attempting to solve this, so no.
The issue can be closed.

**Comment by ninrod** [comment]
@igoralmeida ok thanks!
