### ISSUE TITLE
Is this code released under a license?

### ISSUE THREAD

**Issue by brariden** [timcharper/evil-surround#66]
Hi Tim!

I'm working with a company that only allows licensed software to be downloaded.  I didn't see any in the code - is this released under some open source license?

Thanks in advance!
Bobby

**Comment by timcharper** [comment]
Well, sheesh, I could've sworn I put in "licensed under the same terms as Emacs."

I'll add it now.

**Comment by brariden** [comment]
Awesome - thanks so much!!!
