### ISSUE TITLE
Odd behaviour of evil-surround-region in visual line mode

### ISSUE THREAD

**Issue by fivethousand** [timcharper/evil-surround#71]
#### Description
evil-surround-region behaviour has changed for visual line mode

#### Reproduction guide
- start Emacs
- write a couple of lines, (for example qwe, asd, zxc)
- select lines, press s (or S, whatever maps to evil-surround-region), press {

*Observed behaviour:*
{qwe
asd
zxc}

*Expected behaviour:*
{
qwe
asd
zxc
}

For visual and visual block mode, the observed behaviour is expected and correct, for visual line mode it is wrong imho. This has changed recently, before it did work as expected.

*See*
https://github.com/syl20bnr/spacemacs/issues/5358

**Comment by fivethousand** [comment]
Btw: This deviates from vim-surround.

**Comment by opsound** [comment]
I am seeing the same unexpected behavior.

**Comment by hlissner** [comment]
My bad (my PR made this change)! I'm working on a PR for this now.
