### ISSUE TITLE
Evil-Surround commands are not seen in Which-Key

### ISSUE THREAD

**Issue by a13ph** [timcharper/evil-surround#72]
Even if you add (setq which-key-allow-evil-operators t),
Evil-Surround is not showing which-key popup.

For brief example, on Vs there is no popup, 
as there is none on any other selection I've tried.

Most probably due to its implementation,
it being different than other operators.

I'll give all info you need if anyone fails to repro it.

https://github.com/syl20bnr/spacemacs/issues/5430#issuecomment-194526830

**Comment by ninrod** [comment]
I think you're missing `  (setq which-key-show-operator-state-maps t)`:

```elisp
(use-package which-key :ensure t
      :init
      (setq which-key-allow-evil-operators t)
      (setq which-key-show-operator-state-maps t)
      :config (which-key-mode))
```
