### ISSUE TITLE
Allow to specify delimiter when passing function in visual mode

### ISSUE THREAD

**Issue by asymmetric** [timcharper/evil-surround#75]
Is it possible to allow for more than just `(` when using `Sf` on a visual selection? I have tried entering `text[` in the minibuffer but that didn't seem to work.

**Comment by sooheon** [comment]
Looks like it calls `evil-surround-function`

```
(defun evil-surround-function ()
  "Read a functionname from the minibuffer and wrap selection in function call"
  (let ((fname (read-from-minibuffer "" "" )))
    (cons (format "%s(" (or fname ""))
          ")")))
```

And this is bound to `sf` in the `evil-surround-pairs-alist` defcustom.

So you can try defining your own function `evil-surround-list-access` 

```
(defun evil-surround-list-access ()
  (let ((lname (read-from-minibuffer "" "" )))
    (cons (format "%s[" (or lname ""))
          "]")))
```

And add it to the evil-surround-pairs-alist under the keybinding of your choice. You can even make a PR :)

**Comment by emanresusername** [comment]
has there been any movement on this?

**Comment by ninrod** [comment]
seems that this is unmantained

**Comment by ninrod** [comment]
Yes. I left a comment on your pr.

**Comment by ninrod** [comment]
Since #94 was closed, I'm also closing this related issue.
