### ISSUE TITLE
Newlines support

### ISSUE THREAD

**Issue by lionel-** [timcharper/evil-surround#79]
It would be nice to insert and delete newlines with evil-surround.

For example `ds<RET>` inside:

```
line

paragraph
paragraph

line
```

would result in

```
line
paragraph
paragraph
line
```

**Comment by ninrod** [comment]
this is not supported from @tpope's plugin, which we'd like to keep as the standard, but you should be able to implement a package upon this that would give you this behaviour.

**Comment by MyriaCore** [comment]
Came looking for this functionality. tpope/vim-surround#140 is an open issue in @tpope's plugin. Pending that, would we see this issue re-open?

**Comment by ninrod** [comment]
should the behavior be incorportated in vim-surround, we would re-open the issue, I believe.
