### ISSUE TITLE
regression: the repeat (.) operator broke on commit 66b8f89

### ISSUE THREAD

**Issue by ninrod** [timcharper/evil-surround#84]
If I surround a word, `ysiwb` for example and then try to use the `.` operator to surround another word, I get: `After 0 kbd macro iterations: evil-motion-range: Args out of range: "", 0`

Is this a bug or is the dot operator unsupported? 

thanks in advance.

**Comment by ninrod** [comment]
Hi. I'm getting this in spacemacs from git head (develop branch). 

`After 0 kbd macro iterations: evil-motion-range: Args out of range: "", 0`

steps to reproduce: 

just surround a word with `ysiw"` for example. then try to repeat the operation with the `.` operator. 

what the above message be printed in the minibuffer.

**Comment by sooheon** [comment]
Just to clarify, this is not spacemacs specific. Just a vanilla config of evil-surround has the same error.

**Comment by ninrod** [comment]
Yes. just install evil, install evil-surround, and apply the reproducible procedure.

**Comment by ninrod** [comment]
This really is a core functionality of the package. The whole point of the surround package is to allow the user to repeat the surround operation: surrounding is already covered by vim keybinds: `ciw""<ESC>P` already surrounds the word, but it is not reapeatable.

**Comment by noctuid** [comment]
I have a little experience fixing problems with/adding support for repeating. It may not be too hard to fix, so I'll probably look at it (but it may be a while before I have any time).

**Comment by noctuid** [comment]
I took a quick look, and the problem is that the wrong keystrokes are being recorded for `y` and `c` (e.g. `cs"'` records `csc`; y is just completely wrong). `d` works fine from what I've tested. I may have some time later today to see if it can quickly be fixed. If evil-surround was like [vim-operator-surround](https://github.com/rhysd/vim-operator-surround) and created new operators instead of highjacking existing ones, this would potentially be a lot easier to deal with.

**Comment by sooheon** [comment]
Thank you for looking into it!

**Comment by noctuid** [comment]
Since all the information is available for `c`, a quick fix is pretty simple (in `evil-surround-change`):

```
...
(let ((key (evil-read-key)))
      ;; add these lines
      (setq evil-repeat-info (butlast evil-repeat-info 2))
      (evil-repeat-record (concat (list char key)))
      (evil-repeat-stop)
...
```

This seems to work fine for what I've tried. If this was added, there should be a check to ensure that these modifications are only run for `evil-surround-change` accessed under the `c` operator (e.g. just set some variable in `evil-surround-edit`).

Quickly looking at `y`, I'm not sure if it's possible to fix because `iw` (or whatever the text object/motion key(s) is/are) doesn't appear in `(this-command-keys)` like it normally would. Having the deletion and change bound under `c` and `d` makes sense, but `ys..`'s behavior has nothing to do with `y`, so I don't really think it's that much of a problem to just bind it to its own key. Still, I'll look into an alternate way of doing this when I get the chance.

**Comment by ninrod** [comment]
@noctuid, thanks for your effort on this bug. I've tried the fix for `cs` but it did not rendered the desired results. I do not get an error message, but nothing happens either. 

Am I doing it the right way? here is the [diff](https://github.com/ninrod/evil-surround/commit/c4fdf0ce91205c1e9529ba8901b2f5cc0e3201c6)

**Comment by ninrod** [comment]
Reported on spacemacs: syl20bnr/spacemacs#7662. Seems like a regression of syl20bnr/spacemacs#4641

**Comment by ninrod** [comment]
Funny. In theory #74 should have been the fix for this.

**Comment by ninrod** [comment]
@noctuid, I'm summoning @lislon, the author of #74 who said [this](https://github.com/timcharper/evil-surround/pull/74#issue-144833885):

> I wrapped ys/yS operators with raw record commands, because they
> are handled by evil-yank operator, that is marked as not repeatable. Fixes #24.

@lislon, do you think we've a reggression here?

**Comment by ninrod** [comment]
an interesting test. If we use `ysiw]` and then try to repeat with `.`, I get this:

```elisp
After 0 kbd macro iterations: evil-motion-range: Wrong type argument: commandp, (keymap (keymap (83 . evil-surround-line) (115 . evil-line) (121 . evil-line)) (keymap) (keymap "Auxiliary keymap for Operator-Pending state" (83 . evil-Surround-edit) (115 . evil-surround-edit)) (keymap (105 keymap (74 . evil-indent-plus-i-indent-up-down) (73 . evil-indent-plus-i-indent-up) (105 . evil-indent-plus-i-indent) (97 . evil-inner-arg) (37 . evilmi-inner-text-object) (111 . evil-inner-symbol) (116 . evil-inner-tag) (96 . evil-inner-back-quote) ...) (97 keymap (101 . evil-entire-entire-buffer) (74 . evil-indent-plus-a-indent-up-down) (73 . evil-indent-plus-a-indent-up) (105 . evil-indent-plus-a-indent) (97 . evil-outer-arg) (37 . evilmi-outer-text-object) (111 . evil-a-symbol) (116 . evil-a-tag) ...)) (keymap) (keymap (115 . s-map-prefix) (f8 . eyebrowse-switch-to-window-config-8) (f7 . eyebrowse-switch-to-window-config-7) (f6 . eyebrowse-switch-to-window-config-6) (f5 . eyebrowse-switch-to-window-config-5) (f4 . eyebrowse-switch-to-window-config-4) (f3 . eyebrowse-switch-to-window-config-3) (f2 . eyebrowse-switch-to-window-config-2) (f1 . eyebrowse-switch-to-window-config-1) ...) (keymap (3 keymap (12 . evil-lisp-state-map-prefix))) (keymap (44 . term-map-prefix) "Auxiliary keymap for Normal state") (keymap "Auxiliary keymap for Normal state" (37 . evilmi-jump-items)) ...)
```

**Comment by ninrod** [comment]
confirmed: This is a reggression.

I've performed a git-bisect from master~8 and master and got this results:

```txt
Head:     00f70ac Merge pull request #81 from wbolster/read-keys-with-translation

3e4baf7e203adbb1a57cbb372db17edf1f3a2b90 is the first bad commit

Bisect Rest (1)
3e4baf7 * bad Merge pull request #80 from mineo/doc-fixes

Bisect Log (6)
git bisect start 'master' 'master~8'
c4fdf0c bad wip timcharper/evil-surround#84: first try
a4a04c6 good Merge pull request #74 from lislon/surround-repeat

git bisect bad 3e4baf7e203adbb1a57cbb372db17edf1f3a2b90
3e4baf7 bad Merge pull request #80 from mineo/doc-fixes

git bisect good eda6b0d6ca856d66f32b2718887ff02ea5c94d16
eda6b0d good Merge pull request #78 from vyp/#55

git bisect good 0a61b55d1b76c7aa8a34d2ccb80b5ac351ad94e5
0a61b55 good Move the Keywords after the Mailing list header

git bisect good 00f70acffff1e173262b4ff45f87694e4e0b78ea
00f70ac good Merge pull request #81 from wbolster/read-keys-with-translation

3e4baf7e203adbb1a57cbb372db17edf1f3a2b90 is the first bad commit
```

**Comment by ninrod** [comment]
gentleman, I've fixed it [here](https://github.com/ninrod/evil-surround/commit/85e67d39e75e75b5e202a834c1ebb1ab4a887bac). Basically I've just reverted 66b8f89 and everything is working fine again.

**Comment by noctuid** [comment]
Nice. It doesn't seem like `evil-read-key` is needed for anything here, but it still seems strange that it breaks recording like this. I shouldn't have assumed repeating never worked correctly.

**Comment by wasamasa** [comment]
I'd strongly suggest adding tests to both prove repetition works (for a known set of cases) and to ensure regressions encountered previously don't happen again.

**Comment by ninrod** [comment]
Nice. How can we do that @wasamasa? I'm new in elisp and don't know any test frameworks.

**Comment by sooheon** [comment]
@ninrod The developer of lispy has a very comprehensive test suite here: https://github.com/abo-abo/lispy/blob/master/lispy-test.el

**Comment by wasamasa** [comment]
@ninrod I prefer [buttercup](https://github.com/jorgenschaefer/emacs-buttercup) over ERT, but for that specific kind of tests [ecukes](https://github.com/ecukes/ecukes/) might be a better fit.

**Comment by ninrod** [comment]
@wasamasa thanks for the suggestions. what do you think about [undercover](https://github.com/sviridov/undercover.el)?

**Comment by ninrod** [comment]
can I integrate ecukes with something like travis? same for buttercup?

**Comment by wasamasa** [comment]
Disregard what I've said about ecukes, Evil is simulating key input just fine for its own tests.  I've mistakenly assumed ecukes does something magic...

> what do you think about undercover?

I haven't ever used undercover, so no opinion on it, other than me generally finding code coverage a misleading statistic to strive for.

> can I integrate ecukes with something like travis? same for buttercup?

Sure.

**Comment by ddoherty03** [comment]
I'm new to evil mode and ran into this early in playing with it in spacemacs.  Is the fix up in MELPA yet?
Is there a reason this is still an open issue?

**Comment by ninrod** [comment]
@ddoherty03, It's already fixed on my fork and I've already opened pull request #93, but I think the main reason is that the package creator @timcharper is away and nobody stood up to the task of mantaining the package yet. 

If you want a quick fix, you can use my fork:

git clone my [fork](https://github.com/ninrod/evil-surround) to `~/.emacs.d/lisp/ninrod/evil-surround` and then load it up. for example, using [using-package](https://github.com/jwiegley/use-package):

```elisp
(use-package evil-surround :load-path "lisp/ninrod/evil-surround"
  :config (global-evil-surround-mode 1))
```

working wonderfully for me [here](https://github.com/ninrod/dotfiles/blob/master/emacs/boot.org#evil-surround).

**Comment by ninrod** [comment]
I tried to contact the package author. Let's see if he will respond.

**Comment by ddoherty03** [comment]
Thanks for the explanation ninrod.

**Comment by ddoherty03** [comment]
For anyone wanting to use ninrod's fork in a stock spacemacs, I had to do the following:  (1)
exclude the evil-surround package in dotspacemacs/layers
       
```elisp
dotspacemacs-excluded-packages '(evil-surround)
```
and (2) manually load the local version in dotspacemacs/user-init:

```elisp     
    (with-eval-after-load 'evil
      (progn
        (load "~/.spacemacs.d/ded/lisp/evil-surround/evil-surround.el")
        (global-evil-surround-mode 1)))
```
With the file path changed to where ever you cloned ninrod's fork.

Trying to use ninrod's snippet above did not work in dotspacemacs/user-config because the stock evil-surround was already loaded by then and did not work in dotspacemacs/user-init because use-package was not available at that point.

**Comment by ninrod** [comment]
@ddoherty03, @timcharper gave me push access. I've merged the fix so this should be fixed on melpa in a few hours. Tks.

**Comment by ddoherty03** [comment]
Thanks, @ninrod.  Big help.

**Comment by ninrod** [comment]
np. by the way, you can throw away my fork and use evil-surround directly from melpa now. 

and just a quick tip, when you use the `with-eval-after-load` form you can drop the `progn` form:

```elisp
  (with-eval-after-load 'evil
        (load "~/.spacemacs.d/ded/lisp/evil-surround/evil-surround.el")
        (global-evil-surround-mode 1))
```

this should be sufficient.

**Comment by braham-snyder** [comment]
For what it's worth, #93 makes one-key bindings to `evil-surround-edit` (is that the right way to go about binding a single-key to surround? or does someone know a better way?) repeat their surrounding with either two `i` chars or two `a` chars instead of the desired character, depending on whether an inner/outer textobj was used.

For example, with `r` set to `evil-surround-edit`: `riw".` on `word` gives `i"word"i` instead of `""word""`.

This is not the correct way to fix it, but one really quick fix for those looking for one is to edit the definition of `evil-surround-edit`: just replace the `evil-surround-call-with-repeat` at the very end with `call-interactively`.

**Comment by ninrod** [comment]
@braham-snyder, I don't know if that is supported. Can you you lay down your setup for the "one-key" surround binding?

**Comment by braham-snyder** [comment]
```  
(use-package evil-surround
    :init

    ;;; FIXME: R fails to surround  with newlines
    ;; (for more consistent surround and snipe keys)
    (evil-define-key 'visual evil-surround-mode-map
      "r" 'evil-surround-region
      "R" 'evil-Surround-region)
    (evil-define-key 'operator evil-surround-mode-map
      "r" 'evil-surround-edit
      "R" 'evil-Surround-edit)
    (evil-define-key 'operator evil-surround-mode-map
      "s" nil
      "S" nil)
    ;; stock r and R aren't all that useful--can just use cl/h instead of r, and
    ;; the apex of R's usefulness is on the level of replacing an existing hex
    ;; color with white... no?
    (evil-define-key 'normal evil-surround-mode-map
      "r" 'evil-surround-edit
      "R" 'evil-Surround-edit))
```

**Comment by ninrod** [comment]
shouldn't you place all of those in a `:config` block? seems like those would be clobbed when evil-surround actually loads. Or perhaps use `with-eval-after-load 'evil-surround`?

How are you getting evil-surround with no `:ensure t`? Why no `(global-evil-surround-mode 1)`. 

Just curious.

**Comment by braham-snyder** [comment]
> shouldn't you place all of those in a :config block? seems like those would be clobbed when evil-surround actually loads. Or perhaps use with-eval-after-load 'evil-surround?

@ninrod I was just lazy and fortunate: according to https://www.reddit.com/r/emacs/comments/4e4ja5/lazy_loading_leader_bindings_with_usepackage/d1xfvyk/ `evil-define-key` automatically defers its bindings until the given map actually exists.

> How are you getting evil-surround with no :ensure t?

I'm using Spacemacs, which happens to include `evil-surround` by default--though you might find `(setq use-package-always-ensure t)` useful.

> Why no (global-evil-surround-mode 1)?

Spacemacs sets it elsewhere by default.

**Comment by ninrod** [comment]
@braham-snyder, thanks. Now about that issue of yours, I have some ideas, but please open a separate issue for that.

**Comment by wbolster** [comment]
thanks for NOT mentioning me and blindly reverting my commits.

the "fix" by blindly reverting commits without knowing what they do reintroduces another issue:
https://github.com/timcharper/evil-surround/pull/81

**Comment by ninrod** [comment]
sorry @wbolster, I'm new to all these mantainance stuff. 

can you re-submit a pull that does not reintroduces #24 as a reggression? 

thanks.

**Comment by eeshugerman** [comment]
Anyone know the status of this? Repeat doesn't work for me (in Spacemacs. -- haven't tested in vanilla Emacs). It's unclear to me from the thread above if this is a known issue at this point? It looks like the commit that introduced this regression was reverted, so I guess it's regressed again?

**Comment by ninrod** [comment]
It is working fine, at least to my knowledge. You can confirm with a clean environment using `make emacs` (see instructions in the readme).

**Comment by eeshugerman** [comment]
Thanks @ninrod -- I'm seeing the same behavior with `make emacs` as with my normal install, but I now realize that repeat _mostly_ works fine, but not for `yst<some-char><other-char>`. I'll look into it some more, might open another issue with my findings.

**Comment by ninrod** [comment]
> Thanks @ninrod -- I'm seeing the same behavior with make emacs as with my normal install, but I now realize that repeat mostly works fine, but not for yst<some-char><other-char>. I'll look into it some more, might open another issue with my findings.

Interesting. Keep me posted, please.
