### ISSUE TITLE
evil-surround-change inserts unwanted spaces

### ISSUE THREAD

**Issue by johanatan** [timcharper/evil-surround#86]
i.e., it changes:

`(this-form)`
to:
`[ this-form ]`

Desired functionality: preserve original spacing (or lack thereof).

**Comment by wbolster** [comment]
have you tried using the closing bracket instead of the opening bracket?

**Comment by timcharper** [comment]
@johanatan this is expected behavior. `cs([` will put an extra space around things, and `cs)]` will not.

**Comment by wbolster** [comment]
follow-up question: can this behaviour be swapped? usually i do not want extra space, and opening brackets are easier to reach.

**Comment by johanatan** [comment]
@wbolster  +1. I am actually using this function as my 'r' in SpaceMacs' evil mode and 99 times out of 100 I'm on the opening brace when I want to change them.

I can of course write some elisp to mix in a pair of '%' to get me on the right brace before invoking the function but a better default would be nice.

**Comment by timcharper** [comment]
@wbolster I can certainly why you would want that! Take a look at customizing `evil-surround-pairs-alist` and you should be able to get it to behave as you wish.

A goal of this project is to mimic the vim implementation of surround, so in order to change the default, we'd have to take the discussion upstream.

**Comment by wbolster** [comment]
for reference, this seems to do the trick:

```
;; use non-spaced pairs when surrounding with an opening brace
(evil-add-to-alist
 'evil-surround-pairs-alist
 ?\( '("(" . ")")
 ?\[ '("[" . "]")
 ?\{ '("{" . "}")
 ?\) '("( " . " )")
 ?\] '("[ " . " ]")
 ?\} '("{ " . " }"))
```

...which imho is nicer than overwriting `evil-surround-pairs-alist` completely, which is what the customisation interface would do. (see also #90)

**Comment by wbolster** [comment]
that said, this issue can be closed

**Comment by ninrod** [comment]
ok.

**Comment by didibus** [comment]
@timcharper Vim doesn't have a surround by default? So I'm guessing you are using a plugin in vim for it? In which case, it doesn't feel very standard to me, and I think it would be okay in that case to have a nicer default in evil, which to me would be to have them swapped.
