### ISSUE TITLE
README.md mistake

### ISSUE THREAD

**Issue by Lynolix** [timcharper/evil-surround#91]
Hi there,

In the README.md where you give an example of adding a new pair:
```
(setq-default evil-surround-pairs-alist (cons '(?~ ("``" . "``"))
                                         evil-surround-pairs-alist))
```

Instead it should be :
```
(setq-default evil-surround-pairs-alist (cons '(?~ . ("``" . "``"))
                                         evil-surround-pairs-alist))
```
I thought I'd point it out and save another Elisp newbie from my pain trying to figure out why it wasn't working. Sorry for cluttering the issues otherwise!

**Comment by ninrod** [comment]
Good catch, thank you!
