### ISSUE TITLE
Attempting to change inner quotes actually modifies the most outer quotes

### ISSUE THREAD

**Issue by ZzAntares** [timcharper/evil-surround#92]
Hello, I have a problem, in python having this (cursor is `|` in word `access_token`):

```
            body="""
            {
                "access|_token": "fg123234ksdf9whgelxsurgpr",
                "expires_at": 3600,
                "user_id": "5194"
            }
            """)
```

Doing `cs"'` to change double quotes to single quotes (`"access_token"` to `'access_token'`) produces this:

```
            body='|""
            {
                "access_token": "fg123234ksdf9whgelxsurgpr",
                "expires_at": 3600,
                "user_id": "5194"
            }
            ""')
```

Notice, the most outer double quotes are changed, and cursor changes position.

Is there an easy fix to this?

**Comment by ninrod** [comment]
the `body="""` bit is confusing to the package. Seems like you are opening a multiline string. I think a linewise option should solve the problem, but I'm only starting to learn elisp.

Just curious, how often do you use this sort of triple quotes construct in python?

**Comment by ninrod** [comment]
this is directly related to #56.

**Comment by ninrod** [comment]
closing. duplicate of #56.

**Comment by ZzAntares** [comment]
Thanks @ninrod, about your question that is an extract of a definition of a mock URL using httpretty on python, really I don't use it too often but when I do is annoying that this doesn't work as expected.
